### PR TITLE
ci: set it up

### PR DESCRIPTION
**Pull request by Thomaash**
This just releases so that we can use this in vis-network and others. There is no formatting, linting, building, etc.

### CODE REVIEW

**Comment by mojoaxel** [comment]
Wouldn't it be better to integrate (copy) the type definitions to there visjs repositories and manage them there? I really forgot why I created this repository :confused:

**Comment by Thomaash** [comment]
It wouldn't. With this repo we have our own types under our control. The purpose of DefinitelyTyped is to provide third party types for JavaScript projects that don't provide types of their own.

**Comment by mojoaxel** [comment]
> The purpose of DefinitelyTyped is to provide third party types for JavaScript projects that don't provide types of their own.

yes, we should create an issue there to deprecate `@types/vis` on npm and remove it from the repository. 

But do we need `vis-types`? Why not move everything to the their seperate repository (e.g. vis-network, vis-data...)?

**Comment by Thomaash** [comment]
That's a good question. I can't think of any reason why not. Seems like a good idea to ditch this and partition it into the corresponding packages.

**Comment by Thomaash** [comment]
We're not going to use this repo at all so this is pointless.

**Pull request closed without merging**
