### PR TITLE
chore(CD): set continuous deployment up

### PR DESCRIPTION
**Pull request by Thomaash**
Uses CircleCI and semantic-release.
Every merge into master is released as a new version (on NPM and GitHub), all other branches are ignored.

PS @mojoaxel: I can't set this (or any other repo) up on CircleCI. It says: “You must be an admin to add a project on CircleCI”.

### CODE REVIEW

**Comment by mojoaxel** [comment]
> PS @mojoaxel: I can't set this (or any other repo) up on CircleCI. It says: “You must be an admin to add a project on CircleCI”.

Done!

**Comment by mojoaxel** [comment]
I still think we should not change `vis-types` here but only mirror changes in the upsteam repository. I hope at some point we can integrate all types in the visjs repositories which probably would make `vis-types` and `@types/vis` superfluous!

**Comment by Thomaash** [comment]
DefinitelyTypes is for projects that don't ship their own types but since we now ship our own types we shouldn't use it. Atop of that if we change @types/vis we will break all projects that rely on the legacy vis.

**Comment by mojoaxel** [comment]
> Atop of that if we change @types/vis we will break all projects that rely on the legacy vis.

That's a very good point!!
So `@types/vis` is only for `almende/vis@4.21` and should therefore also be deprecated (but not removed)!
We should get our types up to date and THEN open an issue at DefinitelyTypes with the request to deprecate `@types/vis` in favor of our visjs repositories.

**Pull request closed without merging**
